### ISSUE TITLE
Error: API rate limit exceede

### ISSUE THREAD

**Issue by azzamsa** [extractions/setup-just#9]
Hi.

I have been getting many of this lately:

![image](https://user-images.githubusercontent.com/17734314/208212373-a977b1cf-7d06-4725-83cd-c268a23126c6.png)

```
API rate limit exceeded for 172.176.188.81. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) 
```

- https://github.com/azzamsa/zman/actions/runs/3717496875/jobs/6304905585#step:5:8

Any solution for this?

Thanks for `setup-just`! :heart:

**Comment by azzamsa** [comment]
The issue already addressed here

https://github.com/extractions/setup-just#examples

**Comment by mbhall88** [comment]
I have included my github token as per the examples but am still getting this API rate-limiting error.

**Comment by azzamsa** [comment]
I migrated to https://github.com/taiki-e/install-action

```yaml
      - name: Install latest just release
        uses: taiki-e/install-action@v1
        with:
          tool: just
```
